sudo: required
dist: trusty

os: linux

language: c

compiler:
  - gcc
  - clang

install:
    - sudo apt-get update
    - sudo apt-get install -qq -y cpanminus libluajit-5.1-dev libgd-dev libpcre3-dev cppcheck
    - sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)

script:
  - make
  - prove -lv t
